(define-module beginners.381
  (export abc381a
          abc381b))
(select-module beginners.381)

(define (november-twentytwo? date)
  (define half-pos (quotient (string-length date) 2))
  (define (ones? left-half)
    (string=? left-half (make-string (string-length left-half) #\1)))
  (define (twos? right-half)
    (string=? right-half (make-string (string-length right-half) #\2)))
  (and (odd? (string-length date))
       (char=? #\/ (string-ref date half-pos))
       (ones? (string-copy date 0 half-pos))
       (twos? (string-copy date (+ half-pos 1)))))

(define (abc381a)
  (let* ((n (string->number (read-line)))
         (date (read-line)))
    (if (november-twentytwo? date)
        (print "Yes")
        (print "No"))))

(define (twins? line)
  (define middle (quotient (string-length line) 2))
  (define (twin? i)
    (cond ((>= i middle) #t)
          ((not (char=? (string-ref line (* 2 i)) (string-ref line (+ (* 2 i) 1)))) #f)
          (else (twin? (+ i 1)))))
  (define (count-char-frequencies items)
    (if (null? items)
        '()
        (cons (length (filter (lambda (item) (char=? item (car items))) items))
              (count-char-frequencies (remove (lambda (item) (char=? item (car items))) items)))))
  (and (even? (string-length line))
       (twin? 0)
       (every (lambda (frequency) (= 2 frequency)) (count-char-frequencies (string->list line)))))

(define (abc381b)
  (let ((line (read-line)))
    (if (twins? line)
        (print "Yes")
        (print "No"))))